server:
  port: 8761
eureka:
  instance:
    hostname: eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://www.lin.com:8761/eureka/
  server:
      enable-self-preservation: false