server:
  port: 8888
encrypt:
  key: alin
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xueshuiyy/spring-cloud-config-center.git
          search-paths: clientconfig
          username: xueshuiyy
          password:
      label: master
  security:
    basic:
      enable: true
    user:
      name: root
      password: 123456
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: linRabbit
    username: guest
    password: guest
    connection-timeout: 10000
    template:
      mandatory: true
management:
  endpoints:
    web:
      exposure:
        include: "*"